// -------------------------------------------------------------
//
// Module: firfilt
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2021-01-14 14:46:28
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: firfilt
// InputDataType: numerictype(1,8,7)
// TargetLanguage: Verilog
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form Symmetric FIR
// Filter Length     : 149
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s8,9 -> [-2.500000e-01 2.500000e-01)
// -------------------------------------------------------------
// Multipliers           : 20



`timescale 1 ns / 1 ns

module bc_8
               (
                clk,
                clk_enable,
                reset,
                delay_pipeline,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [7:0] delay_pipeline [0:151]; // sfix8_En7
  output  signed [7:0] filter_out; //sfix8_En7

////////////////////////////////////////////////////////////////
//Module Architecture: firfilt
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [7:0] coeff1 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff2 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff3 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff4 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff5 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff6 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff7 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff8 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff9 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff10 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff11 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff12 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff13 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff14 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff15 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff16 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff17 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff18 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff19 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff20 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff21 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff22 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff23 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff24 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff25 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff26 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff27 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff28 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff29 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff30 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff31 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff32 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff33 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff34 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff35 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff36 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff37 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff38 = 8'b11111110; //sfix8_En9
  parameter signed [7:0] coeff39 = 8'b00000010; //sfix8_En9
  parameter signed [7:0] coeff40 = 8'b11111110; //sfix8_En9
  parameter signed [7:0] coeff41 = 8'b00000010; //sfix8_En9
  parameter signed [7:0] coeff42 = 8'b11111111; //sfix8_En9
  parameter signed [7:0] coeff43 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff44 = 8'b00000001; //sfix8_En9
  parameter signed [7:0] coeff45 = 8'b11111110; //sfix8_En9
  parameter signed [7:0] coeff46 = 8'b00000011; //sfix8_En9
  parameter signed [7:0] coeff47 = 8'b11111100; //sfix8_En9
  parameter signed [7:0] coeff48 = 8'b00000100; //sfix8_En9
  parameter signed [7:0] coeff49 = 8'b11111101; //sfix8_En9
  parameter signed [7:0] coeff50 = 8'b00000010; //sfix8_En9
  parameter signed [7:0] coeff51 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff52 = 8'b11111110; //sfix8_En9
  parameter signed [7:0] coeff53 = 8'b00000100; //sfix8_En9
  parameter signed [7:0] coeff54 = 8'b11111011; //sfix8_En9
  parameter signed [7:0] coeff55 = 8'b00000110; //sfix8_En9
  parameter signed [7:0] coeff56 = 8'b11111010; //sfix8_En9
  parameter signed [7:0] coeff57 = 8'b00000101; //sfix8_En9
  parameter signed [7:0] coeff58 = 8'b11111101; //sfix8_En9
  parameter signed [7:0] coeff59 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff60 = 8'b00000100; //sfix8_En9
  parameter signed [7:0] coeff61 = 8'b11111001; //sfix8_En9
  parameter signed [7:0] coeff62 = 8'b00001010; //sfix8_En9
  parameter signed [7:0] coeff63 = 8'b11110100; //sfix8_En9
  parameter signed [7:0] coeff64 = 8'b00001101; //sfix8_En9
  parameter signed [7:0] coeff65 = 8'b11110101; //sfix8_En9
  parameter signed [7:0] coeff66 = 8'b00000111; //sfix8_En9
  parameter signed [7:0] coeff67 = 8'b00000000; //sfix8_En9
  parameter signed [7:0] coeff68 = 8'b11110111; //sfix8_En9
  parameter signed [7:0] coeff69 = 8'b00010011; //sfix8_En9
  parameter signed [7:0] coeff70 = 8'b11100010; //sfix8_En9
  parameter signed [7:0] coeff71 = 8'b00101000; //sfix8_En9
  parameter signed [7:0] coeff72 = 8'b11001110; //sfix8_En9
  parameter signed [7:0] coeff73 = 8'b00111010; //sfix8_En9
  parameter signed [7:0] coeff74 = 8'b11000010; //sfix8_En9
  parameter signed [7:0] coeff75 = 8'b01000000; //sfix8_En9

  // Signals
  wire signed [8:0] tapsum23; // sfix9_En7
  wire signed [7:0] add_signext; // sfix8_En7
  wire signed [7:0] add_signext_1; // sfix8_En7
  wire signed [8:0] tapsum_mcand; // sfix9_En7
  wire signed [8:0] tapsum24; // sfix9_En7
  wire signed [7:0] add_signext_2; // sfix8_En7
  wire signed [7:0] add_signext_3; // sfix8_En7
  wire signed [8:0] tapsum_mcand_1; // sfix9_En7
  wire signed [8:0] tapsum29; // sfix9_En7
  wire signed [7:0] add_signext_4; // sfix8_En7
  wire signed [7:0] add_signext_5; // sfix8_En7
  wire signed [8:0] tapsum_mcand_2; // sfix9_En7
  wire signed [8:0] tapsum30; // sfix9_En7
  wire signed [7:0] add_signext_6; // sfix8_En7
  wire signed [7:0] add_signext_7; // sfix8_En7
  wire signed [8:0] tapsum_mcand_3; // sfix9_En7
  wire signed [8:0] tapsum31; // sfix9_En7
  wire signed [7:0] add_signext_8; // sfix8_En7
  wire signed [7:0] add_signext_9; // sfix8_En7
  wire signed [8:0] tapsum_mcand_4; // sfix9_En7
  wire signed [8:0] tapsum32; // sfix9_En7
  wire signed [7:0] add_signext_10; // sfix8_En7
  wire signed [7:0] add_signext_11; // sfix8_En7
  wire signed [8:0] tapsum_mcand_5; // sfix9_En7
  wire signed [8:0] tapsum33; // sfix9_En7
  wire signed [7:0] add_signext_12; // sfix8_En7
  wire signed [7:0] add_signext_13; // sfix8_En7
  wire signed [8:0] tapsum_mcand_6; // sfix9_En7
  wire signed [8:0] tapsum34; // sfix9_En7
  wire signed [7:0] add_signext_14; // sfix8_En7
  wire signed [7:0] add_signext_15; // sfix8_En7
  wire signed [8:0] tapsum_mcand_7; // sfix9_En7
  wire signed [8:0] tapsum36; // sfix9_En7
  wire signed [7:0] add_signext_16; // sfix8_En7
  wire signed [7:0] add_signext_17; // sfix8_En7
  wire signed [8:0] tapsum_mcand_8; // sfix9_En7
  wire signed [8:0] tapsum37; // sfix9_En7
  wire signed [7:0] add_signext_18; // sfix8_En7
  wire signed [7:0] add_signext_19; // sfix8_En7
  wire signed [8:0] tapsum_mcand_9; // sfix9_En7
  wire signed [8:0] tapsum38; // sfix9_En7
  wire signed [7:0] add_signext_20; // sfix8_En7
  wire signed [7:0] add_signext_21; // sfix8_En7
  wire signed [8:0] tapsum_mcand_10; // sfix9_En7
  wire signed [8:0] tapsum39; // sfix9_En7
  wire signed [7:0] add_signext_22; // sfix8_En7
  wire signed [7:0] add_signext_23; // sfix8_En7
  wire signed [8:0] tapsum_mcand_11; // sfix9_En7
  wire signed [8:0] tapsum40; // sfix9_En7
  wire signed [7:0] add_signext_24; // sfix8_En7
  wire signed [7:0] add_signext_25; // sfix8_En7
  wire signed [8:0] tapsum_mcand_12; // sfix9_En7
  wire signed [8:0] tapsum41; // sfix9_En7
  wire signed [7:0] add_signext_26; // sfix8_En7
  wire signed [7:0] add_signext_27; // sfix8_En7
  wire signed [8:0] tapsum_mcand_13; // sfix9_En7
  wire signed [8:0] tapsum42; // sfix9_En7
  wire signed [7:0] add_signext_28; // sfix8_En7
  wire signed [7:0] add_signext_29; // sfix8_En7
  wire signed [8:0] tapsum_mcand_14; // sfix9_En7
  wire signed [8:0] tapsum44; // sfix9_En7
  wire signed [7:0] add_signext_30; // sfix8_En7
  wire signed [7:0] add_signext_31; // sfix8_En7
  wire signed [8:0] tapsum_mcand_15; // sfix9_En7
  wire signed [8:0] tapsum45; // sfix9_En7
  wire signed [7:0] add_signext_32; // sfix8_En7
  wire signed [7:0] add_signext_33; // sfix8_En7
  wire signed [8:0] tapsum_mcand_16; // sfix9_En7
  wire signed [8:0] tapsum46; // sfix9_En7
  wire signed [7:0] add_signext_34; // sfix8_En7
  wire signed [7:0] add_signext_35; // sfix8_En7
  wire signed [8:0] tapsum_mcand_17; // sfix9_En7
  wire signed [8:0] tapsum47; // sfix9_En7
  wire signed [7:0] add_signext_36; // sfix8_En7
  wire signed [7:0] add_signext_37; // sfix8_En7
  wire signed [8:0] tapsum_mcand_18; // sfix9_En7
  wire signed [8:0] tapsum48; // sfix9_En7
  wire signed [7:0] add_signext_38; // sfix8_En7
  wire signed [7:0] add_signext_39; // sfix8_En7
  wire signed [8:0] tapsum_mcand_19; // sfix9_En7
  wire signed [8:0] tapsum49; // sfix9_En7
  wire signed [7:0] add_signext_40; // sfix8_En7
  wire signed [7:0] add_signext_41; // sfix8_En7
  wire signed [8:0] tapsum_mcand_20; // sfix9_En7
  wire signed [8:0] tapsum50; // sfix9_En7
  wire signed [7:0] add_signext_42; // sfix8_En7
  wire signed [7:0] add_signext_43; // sfix8_En7
  wire signed [8:0] tapsum_mcand_21; // sfix9_En7
  wire signed [8:0] tapsum52; // sfix9_En7
  wire signed [7:0] add_signext_44; // sfix8_En7
  wire signed [7:0] add_signext_45; // sfix8_En7
  wire signed [8:0] tapsum_mcand_22; // sfix9_En7
  wire signed [8:0] tapsum53; // sfix9_En7
  wire signed [7:0] add_signext_46; // sfix8_En7
  wire signed [7:0] add_signext_47; // sfix8_En7
  wire signed [8:0] tapsum_mcand_23; // sfix9_En7
  wire signed [8:0] tapsum54; // sfix9_En7
  wire signed [7:0] add_signext_48; // sfix8_En7
  wire signed [7:0] add_signext_49; // sfix8_En7
  wire signed [8:0] tapsum_mcand_24; // sfix9_En7
  wire signed [8:0] tapsum55; // sfix9_En7
  wire signed [7:0] add_signext_50; // sfix8_En7
  wire signed [7:0] add_signext_51; // sfix8_En7
  wire signed [8:0] tapsum_mcand_25; // sfix9_En7
  wire signed [8:0] tapsum56; // sfix9_En7
  wire signed [7:0] add_signext_52; // sfix8_En7
  wire signed [7:0] add_signext_53; // sfix8_En7
  wire signed [8:0] tapsum_mcand_26; // sfix9_En7
  wire signed [8:0] tapsum57; // sfix9_En7
  wire signed [7:0] add_signext_54; // sfix8_En7
  wire signed [7:0] add_signext_55; // sfix8_En7
  wire signed [8:0] tapsum_mcand_27; // sfix9_En7
  wire signed [8:0] tapsum58; // sfix9_En7
  wire signed [7:0] add_signext_56; // sfix8_En7
  wire signed [7:0] add_signext_57; // sfix8_En7
  wire signed [8:0] tapsum_mcand_28; // sfix9_En7
  wire signed [8:0] tapsum60; // sfix9_En7
  wire signed [7:0] add_signext_58; // sfix8_En7
  wire signed [7:0] add_signext_59; // sfix8_En7
  wire signed [8:0] tapsum_mcand_29; // sfix9_En7
  wire signed [8:0] tapsum61; // sfix9_En7
  wire signed [7:0] add_signext_60; // sfix8_En7
  wire signed [7:0] add_signext_61; // sfix8_En7
  wire signed [8:0] tapsum_mcand_30; // sfix9_En7
  wire signed [8:0] tapsum62; // sfix9_En7
  wire signed [7:0] add_signext_62; // sfix8_En7
  wire signed [7:0] add_signext_63; // sfix8_En7
  wire signed [8:0] tapsum_mcand_31; // sfix9_En7
  wire signed [8:0] tapsum63; // sfix9_En7
  wire signed [7:0] add_signext_64; // sfix8_En7
  wire signed [7:0] add_signext_65; // sfix8_En7
  wire signed [8:0] tapsum_mcand_32; // sfix9_En7
  wire signed [8:0] tapsum64; // sfix9_En7
  wire signed [7:0] add_signext_66; // sfix8_En7
  wire signed [7:0] add_signext_67; // sfix8_En7
  wire signed [8:0] tapsum_mcand_33; // sfix9_En7
  wire signed [8:0] tapsum65; // sfix9_En7
  wire signed [7:0] add_signext_68; // sfix8_En7
  wire signed [7:0] add_signext_69; // sfix8_En7
  wire signed [8:0] tapsum_mcand_34; // sfix9_En7
  wire signed [8:0] tapsum66; // sfix9_En7
  wire signed [7:0] add_signext_70; // sfix8_En7
  wire signed [7:0] add_signext_71; // sfix8_En7
  wire signed [8:0] tapsum_mcand_35; // sfix9_En7
  wire signed [8:0] tapsum68; // sfix9_En7
  wire signed [7:0] add_signext_72; // sfix8_En7
  wire signed [7:0] add_signext_73; // sfix8_En7
  wire signed [8:0] tapsum_mcand_36; // sfix9_En7
  wire signed [8:0] tapsum69; // sfix9_En7
  wire signed [7:0] add_signext_74; // sfix8_En7
  wire signed [7:0] add_signext_75; // sfix8_En7
  wire signed [8:0] tapsum_mcand_37; // sfix9_En7
  wire signed [8:0] tapsum70; // sfix9_En7
  wire signed [7:0] add_signext_76; // sfix8_En7
  wire signed [7:0] add_signext_77; // sfix8_En7
  wire signed [8:0] tapsum_mcand_38; // sfix9_En7
  wire signed [8:0] tapsum71; // sfix9_En7
  wire signed [7:0] add_signext_78; // sfix8_En7
  wire signed [7:0] add_signext_79; // sfix8_En7
  wire signed [8:0] tapsum_mcand_39; // sfix9_En7
  wire signed [8:0] tapsum72; // sfix9_En7
  wire signed [7:0] add_signext_80; // sfix8_En7
  wire signed [7:0] add_signext_81; // sfix8_En7
  wire signed [8:0] tapsum_mcand_40; // sfix9_En7
  wire signed [8:0] tapsum73; // sfix9_En7
  wire signed [7:0] add_signext_82; // sfix8_En7
  wire signed [7:0] add_signext_83; // sfix8_En7
  wire signed [8:0] tapsum_mcand_41; // sfix9_En7
  wire signed [8:0] tapsum74; // sfix9_En7
  wire signed [7:0] add_signext_84; // sfix8_En7
  wire signed [7:0] add_signext_85; // sfix8_En7
  wire signed [8:0] tapsum_mcand_42; // sfix9_En7
  wire signed [16:0] product75; // sfix17_En16
  wire signed [16:0] product74; // sfix17_En16
  wire signed [16:0] product73; // sfix17_En16
  wire signed [16:0] product72; // sfix17_En16
  wire signed [16:0] product71; // sfix17_En16
  wire signed [16:0] product70; // sfix17_En16
  wire signed [16:0] product69; // sfix17_En16
  wire signed [16:0] product68; // sfix17_En16
  wire signed [16:0] product66; // sfix17_En16
  wire signed [16:0] product65; // sfix17_En16
  wire signed [16:0] product64; // sfix17_En16
  wire signed [16:0] product63; // sfix17_En16
  wire signed [16:0] product62; // sfix17_En16
  wire signed [16:0] product61; // sfix17_En16
  wire signed [16:0] product60; // sfix17_En16
  wire signed [16:0] product58; // sfix17_En16
  wire signed [16:0] product57; // sfix17_En16
  wire signed [16:0] product56; // sfix17_En16
  wire signed [16:0] product55; // sfix17_En16
  wire signed [16:0] product54; // sfix17_En16
  wire signed [16:0] product53; // sfix17_En16
  wire signed [16:0] product52; // sfix17_En16
  wire signed [9:0] mulpwr2_temp; // sfix10_En7
  wire signed [16:0] product50; // sfix17_En16
  wire signed [16:0] product49; // sfix17_En16
  wire signed [16:0] product48; // sfix17_En16
  wire signed [16:0] product47; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_1; // sfix10_En7
  wire signed [16:0] product46; // sfix17_En16
  wire signed [16:0] product45; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_2; // sfix10_En7
  wire signed [16:0] product44; // sfix17_En16
  wire signed [16:0] product42; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_3; // sfix10_En7
  wire signed [16:0] product41; // sfix17_En16
  wire signed [16:0] product40; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_4; // sfix10_En7
  wire signed [16:0] product39; // sfix17_En16
  wire signed [16:0] product38; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_5; // sfix10_En7
  wire signed [16:0] product37; // sfix17_En16
  wire signed [16:0] product36; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_6; // sfix10_En7
  wire signed [16:0] product34; // sfix17_En16
  wire signed [16:0] product33; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_7; // sfix10_En7
  wire signed [16:0] product32; // sfix17_En16
  wire signed [16:0] product31; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_8; // sfix10_En7
  wire signed [16:0] product30; // sfix17_En16
  wire signed [16:0] product29; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_9; // sfix10_En7
  wire signed [16:0] product24; // sfix17_En16
  wire signed [9:0] mulpwr2_temp_10; // sfix10_En7
  wire signed [16:0] product23; // sfix17_En16
  wire signed [23:0] sum1; // sfix24_En16
  wire signed [16:0] add_signext_86; // sfix17_En16
  wire signed [16:0] add_signext_87; // sfix17_En16
  wire signed [17:0] add_temp; // sfix18_En16
  wire signed [23:0] sum2; // sfix24_En16
  wire signed [23:0] add_signext_88; // sfix24_En16
  wire signed [23:0] add_signext_89; // sfix24_En16
  wire signed [24:0] add_temp_1; // sfix25_En16
  wire signed [23:0] sum3; // sfix24_En16
  wire signed [23:0] add_signext_90; // sfix24_En16
  wire signed [23:0] add_signext_91; // sfix24_En16
  wire signed [24:0] add_temp_2; // sfix25_En16
  wire signed [23:0] sum4; // sfix24_En16
  wire signed [23:0] add_signext_92; // sfix24_En16
  wire signed [23:0] add_signext_93; // sfix24_En16
  wire signed [24:0] add_temp_3; // sfix25_En16
  wire signed [23:0] sum5; // sfix24_En16
  wire signed [23:0] add_signext_94; // sfix24_En16
  wire signed [23:0] add_signext_95; // sfix24_En16
  wire signed [24:0] add_temp_4; // sfix25_En16
  wire signed [23:0] sum6; // sfix24_En16
  wire signed [23:0] add_signext_96; // sfix24_En16
  wire signed [23:0] add_signext_97; // sfix24_En16
  wire signed [24:0] add_temp_5; // sfix25_En16
  wire signed [23:0] sum7; // sfix24_En16
  wire signed [23:0] add_signext_98; // sfix24_En16
  wire signed [23:0] add_signext_99; // sfix24_En16
  wire signed [24:0] add_temp_6; // sfix25_En16
  wire signed [23:0] sum8; // sfix24_En16
  wire signed [23:0] add_signext_100; // sfix24_En16
  wire signed [23:0] add_signext_101; // sfix24_En16
  wire signed [24:0] add_temp_7; // sfix25_En16
  wire signed [23:0] sum9; // sfix24_En16
  wire signed [23:0] add_signext_102; // sfix24_En16
  wire signed [23:0] add_signext_103; // sfix24_En16
  wire signed [24:0] add_temp_8; // sfix25_En16
  wire signed [23:0] sum10; // sfix24_En16
  wire signed [23:0] add_signext_104; // sfix24_En16
  wire signed [23:0] add_signext_105; // sfix24_En16
  wire signed [24:0] add_temp_9; // sfix25_En16
  wire signed [23:0] sum11; // sfix24_En16
  wire signed [23:0] add_signext_106; // sfix24_En16
  wire signed [23:0] add_signext_107; // sfix24_En16
  wire signed [24:0] add_temp_10; // sfix25_En16
  wire signed [23:0] sum12; // sfix24_En16
  wire signed [23:0] add_signext_108; // sfix24_En16
  wire signed [23:0] add_signext_109; // sfix24_En16
  wire signed [24:0] add_temp_11; // sfix25_En16
  wire signed [23:0] sum13; // sfix24_En16
  wire signed [23:0] add_signext_110; // sfix24_En16
  wire signed [23:0] add_signext_111; // sfix24_En16
  wire signed [24:0] add_temp_12; // sfix25_En16
  wire signed [23:0] sum14; // sfix24_En16
  wire signed [23:0] add_signext_112; // sfix24_En16
  wire signed [23:0] add_signext_113; // sfix24_En16
  wire signed [24:0] add_temp_13; // sfix25_En16
  wire signed [23:0] sum15; // sfix24_En16
  wire signed [23:0] add_signext_114; // sfix24_En16
  wire signed [23:0] add_signext_115; // sfix24_En16
  wire signed [24:0] add_temp_14; // sfix25_En16
  wire signed [23:0] sum16; // sfix24_En16
  wire signed [23:0] add_signext_116; // sfix24_En16
  wire signed [23:0] add_signext_117; // sfix24_En16
  wire signed [24:0] add_temp_15; // sfix25_En16
  wire signed [23:0] sum17; // sfix24_En16
  wire signed [23:0] add_signext_118; // sfix24_En16
  wire signed [23:0] add_signext_119; // sfix24_En16
  wire signed [24:0] add_temp_16; // sfix25_En16
  wire signed [23:0] sum18; // sfix24_En16
  wire signed [23:0] add_signext_120; // sfix24_En16
  wire signed [23:0] add_signext_121; // sfix24_En16
  wire signed [24:0] add_temp_17; // sfix25_En16
  wire signed [23:0] sum19; // sfix24_En16
  wire signed [23:0] add_signext_122; // sfix24_En16
  wire signed [23:0] add_signext_123; // sfix24_En16
  wire signed [24:0] add_temp_18; // sfix25_En16
  wire signed [23:0] sum20; // sfix24_En16
  wire signed [23:0] add_signext_124; // sfix24_En16
  wire signed [23:0] add_signext_125; // sfix24_En16
  wire signed [24:0] add_temp_19; // sfix25_En16
  wire signed [23:0] sum21; // sfix24_En16
  wire signed [23:0] add_signext_126; // sfix24_En16
  wire signed [23:0] add_signext_127; // sfix24_En16
  wire signed [24:0] add_temp_20; // sfix25_En16
  wire signed [23:0] sum22; // sfix24_En16
  wire signed [23:0] add_signext_128; // sfix24_En16
  wire signed [23:0] add_signext_129; // sfix24_En16
  wire signed [24:0] add_temp_21; // sfix25_En16
  wire signed [23:0] sum23; // sfix24_En16
  wire signed [23:0] add_signext_130; // sfix24_En16
  wire signed [23:0] add_signext_131; // sfix24_En16
  wire signed [24:0] add_temp_22; // sfix25_En16
  wire signed [23:0] sum24; // sfix24_En16
  wire signed [23:0] add_signext_132; // sfix24_En16
  wire signed [23:0] add_signext_133; // sfix24_En16
  wire signed [24:0] add_temp_23; // sfix25_En16
  wire signed [23:0] sum25; // sfix24_En16
  wire signed [23:0] add_signext_134; // sfix24_En16
  wire signed [23:0] add_signext_135; // sfix24_En16
  wire signed [24:0] add_temp_24; // sfix25_En16
  wire signed [23:0] sum26; // sfix24_En16
  wire signed [23:0] add_signext_136; // sfix24_En16
  wire signed [23:0] add_signext_137; // sfix24_En16
  wire signed [24:0] add_temp_25; // sfix25_En16
  wire signed [23:0] sum27; // sfix24_En16
  wire signed [23:0] add_signext_138; // sfix24_En16
  wire signed [23:0] add_signext_139; // sfix24_En16
  wire signed [24:0] add_temp_26; // sfix25_En16
  wire signed [23:0] sum28; // sfix24_En16
  wire signed [23:0] add_signext_140; // sfix24_En16
  wire signed [23:0] add_signext_141; // sfix24_En16
  wire signed [24:0] add_temp_27; // sfix25_En16
  wire signed [23:0] sum29; // sfix24_En16
  wire signed [23:0] add_signext_142; // sfix24_En16
  wire signed [23:0] add_signext_143; // sfix24_En16
  wire signed [24:0] add_temp_28; // sfix25_En16
  wire signed [23:0] sum30; // sfix24_En16
  wire signed [23:0] add_signext_144; // sfix24_En16
  wire signed [23:0] add_signext_145; // sfix24_En16
  wire signed [24:0] add_temp_29; // sfix25_En16
  wire signed [23:0] sum31; // sfix24_En16
  wire signed [23:0] add_signext_146; // sfix24_En16
  wire signed [23:0] add_signext_147; // sfix24_En16
  wire signed [24:0] add_temp_30; // sfix25_En16
  wire signed [23:0] sum32; // sfix24_En16
  wire signed [23:0] add_signext_148; // sfix24_En16
  wire signed [23:0] add_signext_149; // sfix24_En16
  wire signed [24:0] add_temp_31; // sfix25_En16
  wire signed [23:0] sum33; // sfix24_En16
  wire signed [23:0] add_signext_150; // sfix24_En16
  wire signed [23:0] add_signext_151; // sfix24_En16
  wire signed [24:0] add_temp_32; // sfix25_En16
  wire signed [23:0] sum34; // sfix24_En16
  wire signed [23:0] add_signext_152; // sfix24_En16
  wire signed [23:0] add_signext_153; // sfix24_En16
  wire signed [24:0] add_temp_33; // sfix25_En16
  wire signed [23:0] sum35; // sfix24_En16
  wire signed [23:0] add_signext_154; // sfix24_En16
  wire signed [23:0] add_signext_155; // sfix24_En16
  wire signed [24:0] add_temp_34; // sfix25_En16
  wire signed [23:0] sum36; // sfix24_En16
  wire signed [23:0] add_signext_156; // sfix24_En16
  wire signed [23:0] add_signext_157; // sfix24_En16
  wire signed [24:0] add_temp_35; // sfix25_En16
  wire signed [23:0] sum37; // sfix24_En16
  wire signed [23:0] add_signext_158; // sfix24_En16
  wire signed [23:0] add_signext_159; // sfix24_En16
  wire signed [24:0] add_temp_36; // sfix25_En16
  wire signed [23:0] sum38; // sfix24_En16
  wire signed [23:0] add_signext_160; // sfix24_En16
  wire signed [23:0] add_signext_161; // sfix24_En16
  wire signed [24:0] add_temp_37; // sfix25_En16
  wire signed [23:0] sum39; // sfix24_En16
  wire signed [23:0] add_signext_162; // sfix24_En16
  wire signed [23:0] add_signext_163; // sfix24_En16
  wire signed [24:0] add_temp_38; // sfix25_En16
  wire signed [23:0] sum40; // sfix24_En16
  wire signed [23:0] add_signext_164; // sfix24_En16
  wire signed [23:0] add_signext_165; // sfix24_En16
  wire signed [24:0] add_temp_39; // sfix25_En16
  wire signed [23:0] sum41; // sfix24_En16
  wire signed [23:0] add_signext_166; // sfix24_En16
  wire signed [23:0] add_signext_167; // sfix24_En16
  wire signed [24:0] add_temp_40; // sfix25_En16
  wire signed [23:0] sum42; // sfix24_En16
  wire signed [23:0] add_signext_168; // sfix24_En16
  wire signed [23:0] add_signext_169; // sfix24_En16
  wire signed [24:0] add_temp_41; // sfix25_En16
  wire signed [23:0] sum43; // sfix24_En16
  wire signed [23:0] add_signext_170; // sfix24_En16
  wire signed [23:0] add_signext_171; // sfix24_En16
  wire signed [24:0] add_temp_42; // sfix25_En16
  wire signed [7:0] output_typeconvert; // sfix8_En7
  reg  signed [7:0] output_register; // sfix8_En7


  assign add_signext = delay_pipeline[22];
  assign add_signext_1 = delay_pipeline[126];
  assign tapsum23 = add_signext + add_signext_1;

  assign tapsum_mcand = tapsum23;

  assign add_signext_2 = delay_pipeline[23];
  assign add_signext_3 = delay_pipeline[125];
  assign tapsum24 = add_signext_2 + add_signext_3;

  assign tapsum_mcand_1 = tapsum24;

  assign add_signext_4 = delay_pipeline[28];
  assign add_signext_5 = delay_pipeline[120];
  assign tapsum29 = add_signext_4 + add_signext_5;

  assign tapsum_mcand_2 = tapsum29;

  assign add_signext_6 = delay_pipeline[29];
  assign add_signext_7 = delay_pipeline[119];
  assign tapsum30 = add_signext_6 + add_signext_7;

  assign tapsum_mcand_3 = tapsum30;

  assign add_signext_8 = delay_pipeline[30];
  assign add_signext_9 = delay_pipeline[118];
  assign tapsum31 = add_signext_8 + add_signext_9;

  assign tapsum_mcand_4 = tapsum31;

  assign add_signext_10 = delay_pipeline[31];
  assign add_signext_11 = delay_pipeline[117];
  assign tapsum32 = add_signext_10 + add_signext_11;

  assign tapsum_mcand_5 = tapsum32;

  assign add_signext_12 = delay_pipeline[32];
  assign add_signext_13 = delay_pipeline[116];
  assign tapsum33 = add_signext_12 + add_signext_13;

  assign tapsum_mcand_6 = tapsum33;

  assign add_signext_14 = delay_pipeline[33];
  assign add_signext_15 = delay_pipeline[115];
  assign tapsum34 = add_signext_14 + add_signext_15;

  assign tapsum_mcand_7 = tapsum34;

  assign add_signext_16 = delay_pipeline[35];
  assign add_signext_17 = delay_pipeline[113];
  assign tapsum36 = add_signext_16 + add_signext_17;

  assign tapsum_mcand_8 = tapsum36;

  assign add_signext_18 = delay_pipeline[36];
  assign add_signext_19 = delay_pipeline[112];
  assign tapsum37 = add_signext_18 + add_signext_19;

  assign tapsum_mcand_9 = tapsum37;

  assign add_signext_20 = delay_pipeline[37];
  assign add_signext_21 = delay_pipeline[111];
  assign tapsum38 = add_signext_20 + add_signext_21;

  assign tapsum_mcand_10 = tapsum38;

  assign add_signext_22 = delay_pipeline[38];
  assign add_signext_23 = delay_pipeline[110];
  assign tapsum39 = add_signext_22 + add_signext_23;

  assign tapsum_mcand_11 = tapsum39;

  assign add_signext_24 = delay_pipeline[39];
  assign add_signext_25 = delay_pipeline[109];
  assign tapsum40 = add_signext_24 + add_signext_25;

  assign tapsum_mcand_12 = tapsum40;

  assign add_signext_26 = delay_pipeline[40];
  assign add_signext_27 = delay_pipeline[108];
  assign tapsum41 = add_signext_26 + add_signext_27;

  assign tapsum_mcand_13 = tapsum41;

  assign add_signext_28 = delay_pipeline[41];
  assign add_signext_29 = delay_pipeline[107];
  assign tapsum42 = add_signext_28 + add_signext_29;

  assign tapsum_mcand_14 = tapsum42;

  assign add_signext_30 = delay_pipeline[43];
  assign add_signext_31 = delay_pipeline[105];
  assign tapsum44 = add_signext_30 + add_signext_31;

  assign tapsum_mcand_15 = tapsum44;

  assign add_signext_32 = delay_pipeline[44];
  assign add_signext_33 = delay_pipeline[104];
  assign tapsum45 = add_signext_32 + add_signext_33;

  assign tapsum_mcand_16 = tapsum45;

  assign add_signext_34 = delay_pipeline[45];
  assign add_signext_35 = delay_pipeline[103];
  assign tapsum46 = add_signext_34 + add_signext_35;

  assign tapsum_mcand_17 = tapsum46;

  assign add_signext_36 = delay_pipeline[46];
  assign add_signext_37 = delay_pipeline[102];
  assign tapsum47 = add_signext_36 + add_signext_37;

  assign tapsum_mcand_18 = tapsum47;

  assign add_signext_38 = delay_pipeline[47];
  assign add_signext_39 = delay_pipeline[101];
  assign tapsum48 = add_signext_38 + add_signext_39;

  assign tapsum_mcand_19 = tapsum48;

  assign add_signext_40 = delay_pipeline[48];
  assign add_signext_41 = delay_pipeline[100];
  assign tapsum49 = add_signext_40 + add_signext_41;

  assign tapsum_mcand_20 = tapsum49;

  assign add_signext_42 = delay_pipeline[49];
  assign add_signext_43 = delay_pipeline[99];
  assign tapsum50 = add_signext_42 + add_signext_43;

  assign tapsum_mcand_21 = tapsum50;

  assign add_signext_44 = delay_pipeline[51];
  assign add_signext_45 = delay_pipeline[97];
  assign tapsum52 = add_signext_44 + add_signext_45;

  assign tapsum_mcand_22 = tapsum52;

  assign add_signext_46 = delay_pipeline[52];
  assign add_signext_47 = delay_pipeline[96];
  assign tapsum53 = add_signext_46 + add_signext_47;

  assign tapsum_mcand_23 = tapsum53;

  assign add_signext_48 = delay_pipeline[53];
  assign add_signext_49 = delay_pipeline[95];
  assign tapsum54 = add_signext_48 + add_signext_49;

  assign tapsum_mcand_24 = tapsum54;

  assign add_signext_50 = delay_pipeline[54];
  assign add_signext_51 = delay_pipeline[94];
  assign tapsum55 = add_signext_50 + add_signext_51;

  assign tapsum_mcand_25 = tapsum55;

  assign add_signext_52 = delay_pipeline[55];
  assign add_signext_53 = delay_pipeline[93];
  assign tapsum56 = add_signext_52 + add_signext_53;

  assign tapsum_mcand_26 = tapsum56;

  assign add_signext_54 = delay_pipeline[56];
  assign add_signext_55 = delay_pipeline[92];
  assign tapsum57 = add_signext_54 + add_signext_55;

  assign tapsum_mcand_27 = tapsum57;

  assign add_signext_56 = delay_pipeline[57];
  assign add_signext_57 = delay_pipeline[91];
  assign tapsum58 = add_signext_56 + add_signext_57;

  assign tapsum_mcand_28 = tapsum58;

  assign add_signext_58 = delay_pipeline[59];
  assign add_signext_59 = delay_pipeline[89];
  assign tapsum60 = add_signext_58 + add_signext_59;

  assign tapsum_mcand_29 = tapsum60;

  assign add_signext_60 = delay_pipeline[60];
  assign add_signext_61 = delay_pipeline[88];
  assign tapsum61 = add_signext_60 + add_signext_61;

  assign tapsum_mcand_30 = tapsum61;

  assign add_signext_62 = delay_pipeline[61];
  assign add_signext_63 = delay_pipeline[87];
  assign tapsum62 = add_signext_62 + add_signext_63;

  assign tapsum_mcand_31 = tapsum62;

  assign add_signext_64 = delay_pipeline[62];
  assign add_signext_65 = delay_pipeline[86];
  assign tapsum63 = add_signext_64 + add_signext_65;

  assign tapsum_mcand_32 = tapsum63;

  assign add_signext_66 = delay_pipeline[63];
  assign add_signext_67 = delay_pipeline[85];
  assign tapsum64 = add_signext_66 + add_signext_67;

  assign tapsum_mcand_33 = tapsum64;

  assign add_signext_68 = delay_pipeline[64];
  assign add_signext_69 = delay_pipeline[84];
  assign tapsum65 = add_signext_68 + add_signext_69;

  assign tapsum_mcand_34 = tapsum65;

  assign add_signext_70 = delay_pipeline[65];
  assign add_signext_71 = delay_pipeline[83];
  assign tapsum66 = add_signext_70 + add_signext_71;

  assign tapsum_mcand_35 = tapsum66;

  assign add_signext_72 = delay_pipeline[67];
  assign add_signext_73 = delay_pipeline[81];
  assign tapsum68 = add_signext_72 + add_signext_73;

  assign tapsum_mcand_36 = tapsum68;

  assign add_signext_74 = delay_pipeline[68];
  assign add_signext_75 = delay_pipeline[80];
  assign tapsum69 = add_signext_74 + add_signext_75;

  assign tapsum_mcand_37 = tapsum69;

  assign add_signext_76 = delay_pipeline[69];
  assign add_signext_77 = delay_pipeline[79];
  assign tapsum70 = add_signext_76 + add_signext_77;

  assign tapsum_mcand_38 = tapsum70;

  assign add_signext_78 = delay_pipeline[70];
  assign add_signext_79 = delay_pipeline[78];
  assign tapsum71 = add_signext_78 + add_signext_79;

  assign tapsum_mcand_39 = tapsum71;

  assign add_signext_80 = delay_pipeline[71];
  assign add_signext_81 = delay_pipeline[77];
  assign tapsum72 = add_signext_80 + add_signext_81;

  assign tapsum_mcand_40 = tapsum72;

  assign add_signext_82 = delay_pipeline[72];
  assign add_signext_83 = delay_pipeline[76];
  assign tapsum73 = add_signext_82 + add_signext_83;

  assign tapsum_mcand_41 = tapsum73;

  assign add_signext_84 = delay_pipeline[73];
  assign add_signext_85 = delay_pipeline[75];
  assign tapsum74 = add_signext_84 + add_signext_85;

  assign tapsum_mcand_42 = tapsum74;

  assign product75 = $signed({delay_pipeline[74][7:0], 6'b000000});

  assign product74 = tapsum_mcand_42 * coeff74;

  assign product73 = tapsum_mcand_41 * coeff73;

  assign product72 = tapsum_mcand_40 * coeff72;

  assign product71 = tapsum_mcand_39 * coeff71;

  assign product70 = tapsum_mcand_38 * coeff70;

  assign product69 = tapsum_mcand_37 * coeff69;

  assign product68 = tapsum_mcand_36 * coeff68;

  assign product66 = tapsum_mcand_35 * coeff66;

  assign product65 = tapsum_mcand_34 * coeff65;

  assign product64 = tapsum_mcand_33 * coeff64;

  assign product63 = tapsum_mcand_32 * coeff63;

  assign product62 = tapsum_mcand_31 * coeff62;

  assign product61 = tapsum_mcand_30 * coeff61;

  assign product60 = $signed({tapsum_mcand_29[8:0], 2'b00});

  assign product58 = tapsum_mcand_28 * coeff58;

  assign product57 = tapsum_mcand_27 * coeff57;

  assign product56 = tapsum_mcand_26 * coeff56;

  assign product55 = tapsum_mcand_25 * coeff55;

  assign product54 = tapsum_mcand_24 * coeff54;

  assign product53 = $signed({tapsum_mcand_23[8:0], 2'b00});

  assign mulpwr2_temp = (tapsum_mcand_22==9'b100000000) ? $signed({1'b0, tapsum_mcand_22}) : -tapsum_mcand_22;

  assign product52 = $signed({mulpwr2_temp[9:0], 1'b0});

  assign product50 = $signed({tapsum_mcand_21[8:0], 1'b0});

  assign product49 = tapsum_mcand_20 * coeff49;

  assign product48 = $signed({tapsum_mcand_19[8:0], 2'b00});

  assign mulpwr2_temp_1 = (tapsum_mcand_18==9'b100000000) ? $signed({1'b0, tapsum_mcand_18}) : -tapsum_mcand_18;

  assign product47 = $signed({mulpwr2_temp_1[9:0], 2'b00});

  assign product46 = tapsum_mcand_17 * coeff46;

  assign mulpwr2_temp_2 = (tapsum_mcand_16==9'b100000000) ? $signed({1'b0, tapsum_mcand_16}) : -tapsum_mcand_16;

  assign product45 = $signed({mulpwr2_temp_2[9:0], 1'b0});

  assign product44 = $signed({{8{tapsum_mcand_15[8]}}, tapsum_mcand_15});

  assign mulpwr2_temp_3 = (tapsum_mcand_14==9'b100000000) ? $signed({1'b0, tapsum_mcand_14}) : -tapsum_mcand_14;

  assign product42 = $signed({{7{mulpwr2_temp_3[9]}}, mulpwr2_temp_3});

  assign product41 = $signed({tapsum_mcand_13[8:0], 1'b0});

  assign mulpwr2_temp_4 = (tapsum_mcand_12==9'b100000000) ? $signed({1'b0, tapsum_mcand_12}) : -tapsum_mcand_12;

  assign product40 = $signed({mulpwr2_temp_4[9:0], 1'b0});

  assign product39 = $signed({tapsum_mcand_11[8:0], 1'b0});

  assign mulpwr2_temp_5 = (tapsum_mcand_10==9'b100000000) ? $signed({1'b0, tapsum_mcand_10}) : -tapsum_mcand_10;

  assign product38 = $signed({mulpwr2_temp_5[9:0], 1'b0});

  assign product37 = $signed({{8{tapsum_mcand_9[8]}}, tapsum_mcand_9});

  assign mulpwr2_temp_6 = (tapsum_mcand_8==9'b100000000) ? $signed({1'b0, tapsum_mcand_8}) : -tapsum_mcand_8;

  assign product36 = $signed({{7{mulpwr2_temp_6[9]}}, mulpwr2_temp_6});

  assign product34 = $signed({{8{tapsum_mcand_7[8]}}, tapsum_mcand_7});

  assign mulpwr2_temp_7 = (tapsum_mcand_6==9'b100000000) ? $signed({1'b0, tapsum_mcand_6}) : -tapsum_mcand_6;

  assign product33 = $signed({{7{mulpwr2_temp_7[9]}}, mulpwr2_temp_7});

  assign product32 = $signed({{8{tapsum_mcand_5[8]}}, tapsum_mcand_5});

  assign mulpwr2_temp_8 = (tapsum_mcand_4==9'b100000000) ? $signed({1'b0, tapsum_mcand_4}) : -tapsum_mcand_4;

  assign product31 = $signed({{7{mulpwr2_temp_8[9]}}, mulpwr2_temp_8});

  assign product30 = $signed({{8{tapsum_mcand_3[8]}}, tapsum_mcand_3});

  assign mulpwr2_temp_9 = (tapsum_mcand_2==9'b100000000) ? $signed({1'b0, tapsum_mcand_2}) : -tapsum_mcand_2;

  assign product29 = $signed({{7{mulpwr2_temp_9[9]}}, mulpwr2_temp_9});

  assign mulpwr2_temp_10 = (tapsum_mcand_1==9'b100000000) ? $signed({1'b0, tapsum_mcand_1}) : -tapsum_mcand_1;

  assign product24 = $signed({{7{mulpwr2_temp_10[9]}}, mulpwr2_temp_10});

  assign product23 = $signed({{8{tapsum_mcand[8]}}, tapsum_mcand});

  assign add_signext_86 = product23;
  assign add_signext_87 = product24;
  assign add_temp = add_signext_86 + add_signext_87;
  assign sum1 = $signed({{6{add_temp[17]}}, add_temp});

  assign add_signext_88 = sum1;
  assign add_signext_89 = $signed({{7{product29[16]}}, product29});
  assign add_temp_1 = add_signext_88 + add_signext_89;
  assign sum2 = add_temp_1[23:0];

  assign add_signext_90 = sum2;
  assign add_signext_91 = $signed({{7{product30[16]}}, product30});
  assign add_temp_2 = add_signext_90 + add_signext_91;
  assign sum3 = add_temp_2[23:0];

  assign add_signext_92 = sum3;
  assign add_signext_93 = $signed({{7{product31[16]}}, product31});
  assign add_temp_3 = add_signext_92 + add_signext_93;
  assign sum4 = add_temp_3[23:0];

  assign add_signext_94 = sum4;
  assign add_signext_95 = $signed({{7{product32[16]}}, product32});
  assign add_temp_4 = add_signext_94 + add_signext_95;
  assign sum5 = add_temp_4[23:0];

  assign add_signext_96 = sum5;
  assign add_signext_97 = $signed({{7{product33[16]}}, product33});
  assign add_temp_5 = add_signext_96 + add_signext_97;
  assign sum6 = add_temp_5[23:0];

  assign add_signext_98 = sum6;
  assign add_signext_99 = $signed({{7{product34[16]}}, product34});
  assign add_temp_6 = add_signext_98 + add_signext_99;
  assign sum7 = add_temp_6[23:0];

  assign add_signext_100 = sum7;
  assign add_signext_101 = $signed({{7{product36[16]}}, product36});
  assign add_temp_7 = add_signext_100 + add_signext_101;
  assign sum8 = add_temp_7[23:0];

  assign add_signext_102 = sum8;
  assign add_signext_103 = $signed({{7{product37[16]}}, product37});
  assign add_temp_8 = add_signext_102 + add_signext_103;
  assign sum9 = add_temp_8[23:0];

  assign add_signext_104 = sum9;
  assign add_signext_105 = $signed({{7{product38[16]}}, product38});
  assign add_temp_9 = add_signext_104 + add_signext_105;
  assign sum10 = add_temp_9[23:0];

  assign add_signext_106 = sum10;
  assign add_signext_107 = $signed({{7{product39[16]}}, product39});
  assign add_temp_10 = add_signext_106 + add_signext_107;
  assign sum11 = add_temp_10[23:0];

  assign add_signext_108 = sum11;
  assign add_signext_109 = $signed({{7{product40[16]}}, product40});
  assign add_temp_11 = add_signext_108 + add_signext_109;
  assign sum12 = add_temp_11[23:0];

  assign add_signext_110 = sum12;
  assign add_signext_111 = $signed({{7{product41[16]}}, product41});
  assign add_temp_12 = add_signext_110 + add_signext_111;
  assign sum13 = add_temp_12[23:0];

  assign add_signext_112 = sum13;
  assign add_signext_113 = $signed({{7{product42[16]}}, product42});
  assign add_temp_13 = add_signext_112 + add_signext_113;
  assign sum14 = add_temp_13[23:0];

  assign add_signext_114 = sum14;
  assign add_signext_115 = $signed({{7{product44[16]}}, product44});
  assign add_temp_14 = add_signext_114 + add_signext_115;
  assign sum15 = add_temp_14[23:0];

  assign add_signext_116 = sum15;
  assign add_signext_117 = $signed({{7{product45[16]}}, product45});
  assign add_temp_15 = add_signext_116 + add_signext_117;
  assign sum16 = add_temp_15[23:0];

  assign add_signext_118 = sum16;
  assign add_signext_119 = $signed({{7{product46[16]}}, product46});
  assign add_temp_16 = add_signext_118 + add_signext_119;
  assign sum17 = add_temp_16[23:0];

  assign add_signext_120 = sum17;
  assign add_signext_121 = $signed({{7{product47[16]}}, product47});
  assign add_temp_17 = add_signext_120 + add_signext_121;
  assign sum18 = add_temp_17[23:0];

  assign add_signext_122 = sum18;
  assign add_signext_123 = $signed({{7{product48[16]}}, product48});
  assign add_temp_18 = add_signext_122 + add_signext_123;
  assign sum19 = add_temp_18[23:0];

  assign add_signext_124 = sum19;
  assign add_signext_125 = $signed({{7{product49[16]}}, product49});
  assign add_temp_19 = add_signext_124 + add_signext_125;
  assign sum20 = add_temp_19[23:0];

  assign add_signext_126 = sum20;
  assign add_signext_127 = $signed({{7{product50[16]}}, product50});
  assign add_temp_20 = add_signext_126 + add_signext_127;
  assign sum21 = add_temp_20[23:0];

  assign add_signext_128 = sum21;
  assign add_signext_129 = $signed({{7{product52[16]}}, product52});
  assign add_temp_21 = add_signext_128 + add_signext_129;
  assign sum22 = add_temp_21[23:0];

  assign add_signext_130 = sum22;
  assign add_signext_131 = $signed({{7{product53[16]}}, product53});
  assign add_temp_22 = add_signext_130 + add_signext_131;
  assign sum23 = add_temp_22[23:0];

  assign add_signext_132 = sum23;
  assign add_signext_133 = $signed({{7{product54[16]}}, product54});
  assign add_temp_23 = add_signext_132 + add_signext_133;
  assign sum24 = add_temp_23[23:0];

  assign add_signext_134 = sum24;
  assign add_signext_135 = $signed({{7{product55[16]}}, product55});
  assign add_temp_24 = add_signext_134 + add_signext_135;
  assign sum25 = add_temp_24[23:0];

  assign add_signext_136 = sum25;
  assign add_signext_137 = $signed({{7{product56[16]}}, product56});
  assign add_temp_25 = add_signext_136 + add_signext_137;
  assign sum26 = add_temp_25[23:0];

  assign add_signext_138 = sum26;
  assign add_signext_139 = $signed({{7{product57[16]}}, product57});
  assign add_temp_26 = add_signext_138 + add_signext_139;
  assign sum27 = add_temp_26[23:0];

  assign add_signext_140 = sum27;
  assign add_signext_141 = $signed({{7{product58[16]}}, product58});
  assign add_temp_27 = add_signext_140 + add_signext_141;
  assign sum28 = add_temp_27[23:0];

  assign add_signext_142 = sum28;
  assign add_signext_143 = $signed({{7{product60[16]}}, product60});
  assign add_temp_28 = add_signext_142 + add_signext_143;
  assign sum29 = add_temp_28[23:0];

  assign add_signext_144 = sum29;
  assign add_signext_145 = $signed({{7{product61[16]}}, product61});
  assign add_temp_29 = add_signext_144 + add_signext_145;
  assign sum30 = add_temp_29[23:0];

  assign add_signext_146 = sum30;
  assign add_signext_147 = $signed({{7{product62[16]}}, product62});
  assign add_temp_30 = add_signext_146 + add_signext_147;
  assign sum31 = add_temp_30[23:0];

  assign add_signext_148 = sum31;
  assign add_signext_149 = $signed({{7{product63[16]}}, product63});
  assign add_temp_31 = add_signext_148 + add_signext_149;
  assign sum32 = add_temp_31[23:0];

  assign add_signext_150 = sum32;
  assign add_signext_151 = $signed({{7{product64[16]}}, product64});
  assign add_temp_32 = add_signext_150 + add_signext_151;
  assign sum33 = add_temp_32[23:0];

  assign add_signext_152 = sum33;
  assign add_signext_153 = $signed({{7{product65[16]}}, product65});
  assign add_temp_33 = add_signext_152 + add_signext_153;
  assign sum34 = add_temp_33[23:0];

  assign add_signext_154 = sum34;
  assign add_signext_155 = $signed({{7{product66[16]}}, product66});
  assign add_temp_34 = add_signext_154 + add_signext_155;
  assign sum35 = add_temp_34[23:0];

  assign add_signext_156 = sum35;
  assign add_signext_157 = $signed({{7{product68[16]}}, product68});
  assign add_temp_35 = add_signext_156 + add_signext_157;
  assign sum36 = add_temp_35[23:0];

  assign add_signext_158 = sum36;
  assign add_signext_159 = $signed({{7{product69[16]}}, product69});
  assign add_temp_36 = add_signext_158 + add_signext_159;
  assign sum37 = add_temp_36[23:0];

  assign add_signext_160 = sum37;
  assign add_signext_161 = $signed({{7{product70[16]}}, product70});
  assign add_temp_37 = add_signext_160 + add_signext_161;
  assign sum38 = add_temp_37[23:0];

  assign add_signext_162 = sum38;
  assign add_signext_163 = $signed({{7{product71[16]}}, product71});
  assign add_temp_38 = add_signext_162 + add_signext_163;
  assign sum39 = add_temp_38[23:0];

  assign add_signext_164 = sum39;
  assign add_signext_165 = $signed({{7{product72[16]}}, product72});
  assign add_temp_39 = add_signext_164 + add_signext_165;
  assign sum40 = add_temp_39[23:0];

  assign add_signext_166 = sum40;
  assign add_signext_167 = $signed({{7{product73[16]}}, product73});
  assign add_temp_40 = add_signext_166 + add_signext_167;
  assign sum41 = add_temp_40[23:0];

  assign add_signext_168 = sum41;
  assign add_signext_169 = $signed({{7{product74[16]}}, product74});
  assign add_temp_41 = add_signext_168 + add_signext_169;
  assign sum42 = add_temp_41[23:0];

  assign add_signext_170 = sum42;
  assign add_signext_171 = $signed({{7{product75[16]}}, product75});
  assign add_temp_42 = add_signext_170 + add_signext_171;
  assign sum43 = add_temp_42[23:0];

  assign output_typeconvert = sum43[16:9];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // firfilt
