// -------------------------------------------------------------
//
// Module: casfilt
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2021-02-23 21:50:55
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: casfilt
// InputDataType: numerictype(1,10,9)
// TargetLanguage: Verilog
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// Stage 1               : Direct-Form FIR Transposed
// HDL Implementation    : Fully parallel

//
// Stage 2               : Direct-Form Symmetric FIR
// HDL Implementation    : Fully parallel
// Folding Factor        : 1

//
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Cascade
// Number of Stages  : 2
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module casfilt 
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [9:0] filter_in; //sfix10_En9
  output  signed [9:0] filter_out; //sfix10_En9
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: casfilt
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter logical_one = 1'b1; //boolean
  // Signals
  wire signed [9:0] filter_in_stage1; // sfix10_En9
  wire signed [9:0] filter_out_stage1; // sfix10_En9
  wire clk_enable_stage1; // boolean
  wire ce_out_stage1; // boolean
  wire signed [9:0] filter_in_stage2; // sfix10_En9
  wire signed [9:0] filter_out_stage2; // sfix10_En9
  wire clk_enable_stage2; // boolean
  wire ce_out_stage2; // boolean
  wire signed [9:0] filter_in_stage2_tmp; // sfix10_En9
  reg  cedelay1_stage1; // boolean
  reg  cedelay1_stage2; // boolean
  casfilt_stage1 u_casfilt_stage1
    (
    .clk(clk),
    .clk_enable_stage1(clk_enable_stage1),
    .reset(reset),
    .filter_in_stage1(filter_in_stage1),
    .filter_out_stage1(filter_out_stage1)
    );

  casfilt_stage2 u_casfilt_stage2
    (
    .clk(clk),
    .clk_enable_stage2(clk_enable_stage2),
    .reset(reset),
    .filter_in_stage2(filter_in_stage2),
    .filter_out_stage2(filter_out_stage2)
    );


  // Block Statements
  assign filter_in_stage1 = filter_in;
  assign filter_in_stage2_tmp = filter_out_stage1;

  assign filter_in_stage2 = filter_in_stage2_tmp;
  assign clk_enable_stage1 = clk_enable;
  always @ (posedge clk or posedge reset)
    begin: cedelay_stage1_process
      if (reset == 1'b1) begin
        cedelay1_stage1 <= 1'b0;
      end
      else begin
        if (clk_enable_stage1 == 1'b1) begin
          cedelay1_stage1 <= logical_one;
        end
      end
    end // cedelay_stage1_process

  assign ce_out_stage1 =  clk_enable_stage1 & cedelay1_stage1;

  assign clk_enable_stage2 = ce_out_stage1;
  always @ (posedge clk or posedge reset)
    begin: cedelay_stage2_process
      if (reset == 1'b1) begin
        cedelay1_stage2 <= 1'b0;
      end
      else begin
        if (clk_enable_stage2 == 1'b1) begin
          cedelay1_stage2 <= logical_one;
        end
      end
    end // cedelay_stage2_process

  assign ce_out_stage2 =  clk_enable_stage2 & cedelay1_stage2;

  assign ce_out = ce_out_stage2;
  // Assignment Statements
  assign filter_out = filter_out_stage2;
endmodule  // casfilt
