// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2021-02-23 21:48:17
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: casfilt
// InputDataType: numerictype(1,10,9)
// TargetLanguage: Verilog
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR Transposed
// Filter Length     : 73
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s10,9 -> [-1 1)
// -------------------------------------------------------------
// Multipliers           : 5



`timescale 1 ns / 1 ns

module fir3
               (
                clk,
                clk_enable,
                reset,
                product37, // sfix20_En18
                product41, // sfix20_En18
                product49, // sfix20_En18
                product57, // sfix20_En18
                product65, // sfix20_En18
                product73, // sfix20_En18
                negproduct29, // sfix20_En18
                negproduct45, // sfix20_En18
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input signed [19:0] product37; // sfix20_En18
  input signed [19:0] product41; // sfix20_En18
  input signed [19:0] product49; // sfix20_En18
  input signed [19:0] product57; // sfix20_En18
  input signed [19:0] product65; // sfix20_En18
  input signed [19:0] product73; // sfix20_En18
  input signed [19:0] negproduct29; // sfix20_En18
  input signed [19:0] negproduct45; // sfix20_En18

  output  signed [9:0] filter_out; //sfix10_En9

////////////////////////////////////////////////////////////////
//Module Architecture: casfilt_stage1
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants

  reg  signed [9:0] inputreg; // sfix10_En9
  reg  signed [26:0] delay_pipeline [0:71] ; // sfix27_En18
  wire signed [26:0] sumvector [0:71] ; // sfix27_En18

  wire signed [26:0] finalsum; // sfix27_En18
  wire signed [26:0] add_signext; // sfix27_En18
  wire signed [26:0] add_signext_1; // sfix27_En18
  wire signed [27:0] add_temp; // sfix28_En18
  wire signed [26:0] add_signext_2; // sfix27_En18
  wire signed [26:0] add_signext_3; // sfix27_En18
  wire signed [27:0] add_temp_1; // sfix28_En18
  wire signed [26:0] add_signext_4; // sfix27_En18
  wire signed [26:0] add_signext_5; // sfix27_En18
  wire signed [27:0] add_temp_2; // sfix28_En18
  wire signed [26:0] add_signext_6; // sfix27_En18
  wire signed [26:0] add_signext_7; // sfix27_En18
  wire signed [27:0] add_temp_3; // sfix28_En18
  wire signed [26:0] add_signext_8; // sfix27_En18
  wire signed [26:0] add_signext_9; // sfix27_En18
  wire signed [27:0] add_temp_4; // sfix28_En18
  wire signed [26:0] add_signext_10; // sfix27_En18
  wire signed [26:0] add_signext_11; // sfix27_En18
  wire signed [27:0] add_temp_5; // sfix28_En18
  wire signed [26:0] add_signext_12; // sfix27_En18
  wire signed [26:0] add_signext_13; // sfix27_En18
  wire signed [27:0] add_temp_6; // sfix28_En18
  wire signed [26:0] add_signext_14; // sfix27_En18
  wire signed [26:0] add_signext_15; // sfix27_En18
  wire signed [27:0] add_temp_7; // sfix28_En18
  wire signed [26:0] add_signext_16; // sfix27_En18
  wire signed [26:0] add_signext_17; // sfix27_En18
  wire signed [27:0] add_temp_8; // sfix28_En18
  wire signed [26:0] add_signext_18; // sfix27_En18
  wire signed [26:0] add_signext_19; // sfix27_En18
  wire signed [27:0] add_temp_9; // sfix28_En18
  wire signed [26:0] add_signext_20; // sfix27_En18
  wire signed [26:0] add_signext_21; // sfix27_En18
  wire signed [27:0] add_temp_10; // sfix28_En18
  wire signed [26:0] add_signext_22; // sfix27_En18
  wire signed [26:0] add_signext_23; // sfix27_En18
  wire signed [27:0] add_temp_11; // sfix28_En18
  wire signed [26:0] add_signext_24; // sfix27_En18
  wire signed [26:0] add_signext_25; // sfix27_En18
  wire signed [27:0] add_temp_12; // sfix28_En18
  wire signed [26:0] add_signext_26; // sfix27_En18
  wire signed [26:0] add_signext_27; // sfix27_En18
  wire signed [27:0] add_temp_13; // sfix28_En18
  wire signed [9:0] output_typeconvert; // sfix10_En9

  always @ (posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
        delay_pipeline[65] <= 0;
        delay_pipeline[66] <= 0;
        delay_pipeline[67] <= 0;
        delay_pipeline[68] <= 0;
        delay_pipeline[69] <= 0;
        delay_pipeline[70] <= 0;
        delay_pipeline[71] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= sumvector[0];
          delay_pipeline[1] <= sumvector[1];
          delay_pipeline[2] <= sumvector[2];
          delay_pipeline[3] <= sumvector[3];
          delay_pipeline[4] <= sumvector[4];
          delay_pipeline[5] <= sumvector[5];
          delay_pipeline[6] <= sumvector[6];
          delay_pipeline[7] <= sumvector[7];
          delay_pipeline[8] <= sumvector[8];
          delay_pipeline[9] <= sumvector[9];
          delay_pipeline[10] <= sumvector[10];
          delay_pipeline[11] <= sumvector[11];
          delay_pipeline[12] <= sumvector[12];
          delay_pipeline[13] <= sumvector[13];
          delay_pipeline[14] <= sumvector[14];
          delay_pipeline[15] <= sumvector[15];
          delay_pipeline[16] <= sumvector[16];
          delay_pipeline[17] <= sumvector[17];
          delay_pipeline[18] <= sumvector[18];
          delay_pipeline[19] <= sumvector[19];
          delay_pipeline[20] <= sumvector[20];
          delay_pipeline[21] <= sumvector[21];
          delay_pipeline[22] <= sumvector[22];
          delay_pipeline[23] <= sumvector[23];
          delay_pipeline[24] <= sumvector[24];
          delay_pipeline[25] <= sumvector[25];
          delay_pipeline[26] <= sumvector[26];
          delay_pipeline[27] <= sumvector[27];
          delay_pipeline[28] <= sumvector[28];
          delay_pipeline[29] <= sumvector[29];
          delay_pipeline[30] <= sumvector[30];
          delay_pipeline[31] <= sumvector[31];
          delay_pipeline[32] <= sumvector[32];
          delay_pipeline[33] <= sumvector[33];
          delay_pipeline[34] <= sumvector[34];
          delay_pipeline[35] <= sumvector[35];
          delay_pipeline[36] <= sumvector[36];
          delay_pipeline[37] <= sumvector[37];
          delay_pipeline[38] <= sumvector[38];
          delay_pipeline[39] <= sumvector[39];
          delay_pipeline[40] <= sumvector[40];
          delay_pipeline[41] <= sumvector[41];
          delay_pipeline[42] <= sumvector[42];
          delay_pipeline[43] <= sumvector[43];
          delay_pipeline[44] <= sumvector[44];
          delay_pipeline[45] <= sumvector[45];
          delay_pipeline[46] <= sumvector[46];
          delay_pipeline[47] <= sumvector[47];
          delay_pipeline[48] <= sumvector[48];
          delay_pipeline[49] <= sumvector[49];
          delay_pipeline[50] <= sumvector[50];
          delay_pipeline[51] <= sumvector[51];
          delay_pipeline[52] <= sumvector[52];
          delay_pipeline[53] <= sumvector[53];
          delay_pipeline[54] <= sumvector[54];
          delay_pipeline[55] <= sumvector[55];
          delay_pipeline[56] <= sumvector[56];
          delay_pipeline[57] <= sumvector[57];
          delay_pipeline[58] <= sumvector[58];
          delay_pipeline[59] <= sumvector[59];
          delay_pipeline[60] <= sumvector[60];
          delay_pipeline[61] <= sumvector[61];
          delay_pipeline[62] <= sumvector[62];
          delay_pipeline[63] <= sumvector[63];
          delay_pipeline[64] <= sumvector[64];
          delay_pipeline[65] <= sumvector[65];
          delay_pipeline[66] <= sumvector[66];
          delay_pipeline[67] <= sumvector[67];
          delay_pipeline[68] <= sumvector[68];
          delay_pipeline[69] <= sumvector[69];
          delay_pipeline[70] <= sumvector[70];
          delay_pipeline[71] <= sumvector[71];
        end
      end
    end // Delay_Pipeline_process

  assign add_signext = $signed({{7{product73[19]}}, product73});
  assign add_signext_1 = delay_pipeline[0];
  assign add_temp = add_signext + add_signext_1;
  assign finalsum = add_temp[26:0];

  assign sumvector[0] = delay_pipeline[1];

  assign sumvector[1] = delay_pipeline[2];

  assign sumvector[2] = delay_pipeline[3];

  assign sumvector[3] = delay_pipeline[4];

  assign sumvector[4] = delay_pipeline[5];

  assign sumvector[5] = delay_pipeline[6];

  assign sumvector[6] = delay_pipeline[7];

  assign add_signext_2 = $signed({{7{product65[19]}}, product65});
  assign add_signext_3 = delay_pipeline[8];
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sumvector[7] = add_temp_1[26:0];

  assign sumvector[8] = delay_pipeline[9];

  assign sumvector[9] = delay_pipeline[10];

  assign sumvector[10] = delay_pipeline[11];

  assign sumvector[11] = delay_pipeline[12];

  assign sumvector[12] = delay_pipeline[13];

  assign sumvector[13] = delay_pipeline[14];

  assign sumvector[14] = delay_pipeline[15];

  assign add_signext_4 = $signed({{7{product57[19]}}, product57});
  assign add_signext_5 = delay_pipeline[16];
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sumvector[15] = add_temp_2[26:0];

  assign sumvector[16] = delay_pipeline[17];

  assign sumvector[17] = delay_pipeline[18];

  assign sumvector[18] = delay_pipeline[19];

  assign add_signext_6 = $signed({{7{product73[19]}}, product73});
  assign add_signext_7 = delay_pipeline[20];
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sumvector[19] = add_temp_3[26:0];

  assign sumvector[20] = delay_pipeline[21];

  assign sumvector[21] = delay_pipeline[22];

  assign sumvector[22] = delay_pipeline[23];

  assign add_signext_8 = $signed({{7{product49[19]}}, product49});
  assign add_signext_9 = delay_pipeline[24];
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sumvector[23] = add_temp_4[26:0];

  assign sumvector[24] = delay_pipeline[25];

  assign sumvector[25] = delay_pipeline[26];

  assign sumvector[26] = delay_pipeline[27];

  assign add_signext_10 = $signed({{7{negproduct29[19]}}, negproduct29});
  assign add_signext_11 = delay_pipeline[28];
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sumvector[27] = add_temp_5[26:0];

  assign sumvector[28] = delay_pipeline[29];

  assign sumvector[29] = delay_pipeline[30];

  assign sumvector[30] = delay_pipeline[31];

  assign add_signext_12 = $signed({{7{product41[19]}}, product41});
  assign add_signext_13 = delay_pipeline[32];
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sumvector[31] = add_temp_6[26:0];

  assign sumvector[32] = delay_pipeline[33];

  assign sumvector[33] = delay_pipeline[34];

  assign sumvector[34] = delay_pipeline[35];

  assign add_signext_14 = $signed({{7{product37[19]}}, product37});
  assign add_signext_15 = delay_pipeline[36];
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sumvector[35] = add_temp_7[26:0];

  assign sumvector[36] = delay_pipeline[37];

  assign sumvector[37] = delay_pipeline[38];

  assign sumvector[38] = delay_pipeline[39];

  assign add_signext_16 = $signed({{7{product41[19]}}, product41});
  assign add_signext_17 = delay_pipeline[40];
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sumvector[39] = add_temp_8[26:0];

  assign sumvector[40] = delay_pipeline[41];

  assign sumvector[41] = delay_pipeline[42];

  assign sumvector[42] = delay_pipeline[43];

  assign add_signext_18 = $signed({{7{negproduct45[19]}}, negproduct45});
  assign add_signext_19 = delay_pipeline[44];
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sumvector[43] = add_temp_9[26:0];

  assign sumvector[44] = delay_pipeline[45];

  assign sumvector[45] = delay_pipeline[46];

  assign sumvector[46] = delay_pipeline[47];

  assign add_signext_20 = $signed({{7{product49[19]}}, product49});
  assign add_signext_21 = delay_pipeline[48];
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sumvector[47] = add_temp_10[26:0];

  assign sumvector[48] = delay_pipeline[49];

  assign sumvector[49] = delay_pipeline[50];

  assign sumvector[50] = delay_pipeline[51];

  assign add_signext_22 = $signed({{7{product73[19]}}, product73});
  assign add_signext_23 = delay_pipeline[52];
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sumvector[51] = add_temp_11[26:0];

  assign sumvector[52] = delay_pipeline[53];

  assign sumvector[53] = delay_pipeline[54];

  assign sumvector[54] = delay_pipeline[55];

  assign add_signext_24 = $signed({{7{product57[19]}}, product57});
  assign add_signext_25 = delay_pipeline[56];
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sumvector[55] = add_temp_12[26:0];

  assign sumvector[56] = delay_pipeline[57];

  assign sumvector[57] = delay_pipeline[58];

  assign sumvector[58] = delay_pipeline[59];

  assign sumvector[59] = delay_pipeline[60];

  assign sumvector[60] = delay_pipeline[61];

  assign sumvector[61] = delay_pipeline[62];

  assign sumvector[62] = delay_pipeline[63];

  assign add_signext_26 = $signed({{7{product65[19]}}, product65});
  assign add_signext_27 = delay_pipeline[64];
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sumvector[63] = add_temp_13[26:0];

  assign sumvector[64] = delay_pipeline[65];

  assign sumvector[65] = delay_pipeline[66];

  assign sumvector[66] = delay_pipeline[67];

  assign sumvector[67] = delay_pipeline[68];

  assign sumvector[68] = delay_pipeline[69];

  assign sumvector[69] = delay_pipeline[70];

  assign sumvector[70] = delay_pipeline[71];

  assign sumvector[71] = $signed({{7{product73[19]}}, product73});

  assign output_typeconvert = finalsum[18:9];

  // Assignment Statements
  assign filter_out = output_typeconvert;
endmodule  // casfilt_stage1
