// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 9.8 and Filter Design HDL Coder 3.1.7.
// Generated on: 2021-01-22 10:32:15
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: casfilt
// InputDataType: numerictype(1,8,7)
// TargetLanguage: Verilog
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form Symmetric FIR
// Filter Length     : 77
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s8,7 -> [-1 1)
// -------------------------------------------------------------
// Multipliers           : 6



`timescale 1 ns / 1 ns

module mult_out
               (
                tapsum_mcand,
                tapsum_mcand_1,
                tapsum_mcand_2,
                tapsum_mcand_3,
                tapsum_mcand_4,
                tapsum_mcand_5,
                tapsum_mcand_6,
                tapsum_mcand_7,
                tapsum_mcand_8,
                tapsum_mcand_9,
                tapsum_mcand_10,
                tapsum_mcand_11,
                tapsum_mcand_12,
                tapsum_mcand_13,
                tapsum_mcand_14,
                filter_out
                );

  input signed [10:0] tapsum_mcand; // sfix11_En9
  input signed [10:0] tapsum_mcand_1; // sfix11_En9
  input signed [10:0] tapsum_mcand_2; // sfix9_En7
  input signed [10:0] tapsum_mcand_3; // sfix9_En7
  input signed [10:0] tapsum_mcand_4; // sfix9_En7
  input signed [10:0] tapsum_mcand_5; // sfix9_En7  
  input signed [10:0] tapsum_mcand_6; // sfix9_En7
  input signed [10:0] tapsum_mcand_7; // sfix9_En7
  input signed [10:0] tapsum_mcand_8; // sfix9_En7
  input signed [10:0] tapsum_mcand_9; // sfix9_En7
  input signed [10:0] tapsum_mcand_10; // sfix9_En7
  input signed [10:0] tapsum_mcand_11; // sfix9_En7
  input signed [10:0] tapsum_mcand_12; // sfix9_En7
  input signed [10:0] tapsum_mcand_13; // sfix9_En7
  input signed [9:0] tapsum_mcand_14; // sfix9_En7

  output signed [9:0] filter_out; //sfix8_En7

////////////////////////////////////////////////////////////////
//Module Architecture: casfilt_stage2
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [9:0] coeff1 = 10'b0000000000; //sfix10_En9
  parameter signed [9:0] coeff2 = 10'b0000000000; //sfix10_En9
  parameter signed [9:0] coeff3 = 10'b0000000000; //sfix10_En9
  parameter signed [9:0] coeff4 = 10'b0000000000; //sfix10_En9
  parameter signed [9:0] coeff5 = 10'b1111111111; //sfix10_En9
  parameter signed [9:0] coeff6 = 10'b0000000000; //sfix10_En9
  parameter signed [9:0] coeff7 = 10'b0000000010; //sfix10_En9
  parameter signed [9:0] coeff8 = 10'b0000000001; //sfix10_En9
  parameter signed [9:0] coeff9 = 10'b1111111011; //sfix10_En9
  parameter signed [9:0] coeff10 = 10'b1111111111; //sfix10_En9
  parameter signed [9:0] coeff11 = 10'b0000001001; //sfix10_En9
  parameter signed [9:0] coeff12 = 10'b0000000001; //sfix10_En9
  parameter signed [9:0] coeff13 = 10'b1111110001; //sfix10_En9
  parameter signed [9:0] coeff14 = 10'b1111111111; //sfix10_En9
  parameter signed [9:0] coeff15 = 10'b0000011010; //sfix10_En9
  parameter signed [9:0] coeff16 = 10'b0000000010; //sfix10_En9
  parameter signed [9:0] coeff17 = 10'b1111001110; //sfix10_En9
  parameter signed [9:0] coeff18 = 10'b1111111110; //sfix10_En9
  parameter signed [9:0] coeff19 = 10'b0010100010; //sfix10_En9
  parameter signed [9:0] coeff20 = 10'b0100000010; //sfix10_En9

   wire signed [20:0] product20; // sfix21_En18
  wire signed [19:0] mul_temp; // sfix20_En18
  wire signed [20:0] product19; // sfix21_En18
  wire signed [20:0] product18; // sfix21_En18
  wire signed [11:0] mulpwr2_temp; // sfix12_En9
  wire signed [20:0] product17; // sfix21_En18
  wire signed [20:0] product16; // sfix21_En18
  wire signed [20:0] product15; // sfix21_En18
  wire signed [20:0] product14; // sfix21_En18
  wire signed [11:0] mulpwr2_temp_1; // sfix12_En9
  wire signed [20:0] product13; // sfix21_En18
  wire signed [20:0] product12; // sfix21_En18
  wire signed [20:0] product11; // sfix21_En18
  wire signed [20:0] product10; // sfix21_En18
  wire signed [11:0] mulpwr2_temp_2; // sfix12_En9
  wire signed [20:0] product9; // sfix21_En18
  wire signed [20:0] product8; // sfix21_En18
  wire signed [20:0] product7; // sfix21_En18
  wire signed [20:0] product5; // sfix21_En18
  wire signed [11:0] mulpwr2_temp_3; // sfix12_En9
  wire signed [25:0] sum1; // sfix26_En18
  wire signed [20:0] add_signext_28; // sfix21_En18
  wire signed [20:0] add_signext_29; // sfix21_En18
  wire signed [21:0] add_temp; // sfix22_En18
  wire signed [25:0] sum2; // sfix26_En18
  wire signed [25:0] add_signext_30; // sfix26_En18
  wire signed [25:0] add_signext_31; // sfix26_En18
  wire signed [26:0] add_temp_1; // sfix27_En18
  wire signed [25:0] sum3; // sfix26_En18
  wire signed [25:0] add_signext_32; // sfix26_En18
  wire signed [25:0] add_signext_33; // sfix26_En18
  wire signed [26:0] add_temp_2; // sfix27_En18
  wire signed [25:0] sum4; // sfix26_En18
  wire signed [25:0] add_signext_34; // sfix26_En18
  wire signed [25:0] add_signext_35; // sfix26_En18
  wire signed [26:0] add_temp_3; // sfix27_En18
  wire signed [25:0] sum5; // sfix26_En18
  wire signed [25:0] add_signext_36; // sfix26_En18
  wire signed [25:0] add_signext_37; // sfix26_En18
  wire signed [26:0] add_temp_4; // sfix27_En18
  wire signed [25:0] sum6; // sfix26_En18
  wire signed [25:0] add_signext_38; // sfix26_En18
  wire signed [25:0] add_signext_39; // sfix26_En18
  wire signed [26:0] add_temp_5; // sfix27_En18
  wire signed [25:0] sum7; // sfix26_En18
  wire signed [25:0] add_signext_40; // sfix26_En18
  wire signed [25:0] add_signext_41; // sfix26_En18
  wire signed [26:0] add_temp_6; // sfix27_En18
  wire signed [25:0] sum8; // sfix26_En18
  wire signed [25:0] add_signext_42; // sfix26_En18
  wire signed [25:0] add_signext_43; // sfix26_En18
  wire signed [26:0] add_temp_7; // sfix27_En18
  wire signed [25:0] sum9; // sfix26_En18
  wire signed [25:0] add_signext_44; // sfix26_En18
  wire signed [25:0] add_signext_45; // sfix26_En18
  wire signed [26:0] add_temp_8; // sfix27_En18
  wire signed [25:0] sum10; // sfix26_En18
  wire signed [25:0] add_signext_46; // sfix26_En18
  wire signed [25:0] add_signext_47; // sfix26_En18
  wire signed [26:0] add_temp_9; // sfix27_En18
  wire signed [25:0] sum11; // sfix26_En18
  wire signed [25:0] add_signext_48; // sfix26_En18
  wire signed [25:0] add_signext_49; // sfix26_En18
  wire signed [26:0] add_temp_10; // sfix27_En18
  wire signed [25:0] sum12; // sfix26_En18
  wire signed [25:0] add_signext_50; // sfix26_En18
  wire signed [25:0] add_signext_51; // sfix26_En18
  wire signed [26:0] add_temp_11; // sfix27_En18
  wire signed [25:0] sum13; // sfix26_En18
  wire signed [25:0] add_signext_52; // sfix26_En18
  wire signed [25:0] add_signext_53; // sfix26_En18
  wire signed [26:0] add_temp_12; // sfix27_En18
  wire signed [25:0] sum14; // sfix26_En18
  wire signed [25:0] add_signext_54; // sfix26_En18
  wire signed [25:0] add_signext_55; // sfix26_En18
  wire signed [26:0] add_temp_13; // sfix27_En18
  wire signed [9:0] output_typeconvert; // sfix10_En9

  assign mul_temp = tapsum_mcand_14 * coeff20;

  assign product20 = $signed({{1{mul_temp[19]}}, mul_temp});

  assign product19 = tapsum_mcand_13 * coeff19;

  assign mulpwr2_temp = (tapsum_mcand_12==11'b10000000000) ? $signed({1'b0, tapsum_mcand_12}) : -tapsum_mcand_12;

  assign product18 = $signed({mulpwr2_temp[11:0], 1'b0});

  assign product17 = tapsum_mcand_11 * coeff17;

  assign product16 = $signed({tapsum_mcand_10[10:0], 1'b0});

  assign product15 = tapsum_mcand_9 * coeff15;

  assign mulpwr2_temp_1 = (tapsum_mcand_8==11'b10000000000) ? $signed({1'b0, tapsum_mcand_8}) : -tapsum_mcand_8;

  assign product14 = $signed({{9{mulpwr2_temp_1[11]}}, mulpwr2_temp_1});

  assign product13 = tapsum_mcand_7 * coeff13;

  assign product12 = $signed({{10{tapsum_mcand_6[10]}}, tapsum_mcand_6});

  assign product11 = tapsum_mcand_5 * coeff11;

  assign mulpwr2_temp_2 = (tapsum_mcand_4==11'b10000000000) ? $signed({1'b0, tapsum_mcand_4}) : -tapsum_mcand_4;

  assign product10 = $signed({{9{mulpwr2_temp_2[11]}}, mulpwr2_temp_2});

  assign product9 = tapsum_mcand_3 * coeff9;

  assign product8 = $signed({{10{tapsum_mcand_2[10]}}, tapsum_mcand_2});

  assign product7 = $signed({tapsum_mcand_1[10:0], 1'b0});

  assign mulpwr2_temp_3 = (tapsum_mcand==11'b10000000000) ? $signed({1'b0, tapsum_mcand}) : -tapsum_mcand;

  assign product5 = $signed({{9{mulpwr2_temp_3[11]}}, mulpwr2_temp_3});

  assign add_signext_28 = product5;
  assign add_signext_29 = product7;
  assign add_temp = add_signext_28 + add_signext_29;
  assign sum1 = $signed({{4{add_temp[21]}}, add_temp});

  assign add_signext_30 = sum1;
  assign add_signext_31 = $signed({{5{product8[20]}}, product8});
  assign add_temp_1 = add_signext_30 + add_signext_31;
  assign sum2 = add_temp_1[25:0];

  assign add_signext_32 = sum2;
  assign add_signext_33 = $signed({{5{product9[20]}}, product9});
  assign add_temp_2 = add_signext_32 + add_signext_33;
  assign sum3 = add_temp_2[25:0];

  assign add_signext_34 = sum3;
  assign add_signext_35 = $signed({{5{product10[20]}}, product10});
  assign add_temp_3 = add_signext_34 + add_signext_35;
  assign sum4 = add_temp_3[25:0];

  assign add_signext_36 = sum4;
  assign add_signext_37 = $signed({{5{product11[20]}}, product11});
  assign add_temp_4 = add_signext_36 + add_signext_37;
  assign sum5 = add_temp_4[25:0];

  assign add_signext_38 = sum5;
  assign add_signext_39 = $signed({{5{product12[20]}}, product12});
  assign add_temp_5 = add_signext_38 + add_signext_39;
  assign sum6 = add_temp_5[25:0];

  assign add_signext_40 = sum6;
  assign add_signext_41 = $signed({{5{product13[20]}}, product13});
  assign add_temp_6 = add_signext_40 + add_signext_41;
  assign sum7 = add_temp_6[25:0];

  assign add_signext_42 = sum7;
  assign add_signext_43 = $signed({{5{product14[20]}}, product14});
  assign add_temp_7 = add_signext_42 + add_signext_43;
  assign sum8 = add_temp_7[25:0];

  assign add_signext_44 = sum8;
  assign add_signext_45 = $signed({{5{product15[20]}}, product15});
  assign add_temp_8 = add_signext_44 + add_signext_45;
  assign sum9 = add_temp_8[25:0];

  assign add_signext_46 = sum9;
  assign add_signext_47 = $signed({{5{product16[20]}}, product16});
  assign add_temp_9 = add_signext_46 + add_signext_47;
  assign sum10 = add_temp_9[25:0];

  assign add_signext_48 = sum10;
  assign add_signext_49 = $signed({{5{product17[20]}}, product17});
  assign add_temp_10 = add_signext_48 + add_signext_49;
  assign sum11 = add_temp_10[25:0];

  assign add_signext_50 = sum11;
  assign add_signext_51 = $signed({{5{product18[20]}}, product18});
  assign add_temp_11 = add_signext_50 + add_signext_51;
  assign sum12 = add_temp_11[25:0];

  assign add_signext_52 = sum12;
  assign add_signext_53 = $signed({{5{product19[20]}}, product19});
  assign add_temp_12 = add_signext_52 + add_signext_53;
  assign sum13 = add_temp_12[25:0];

  assign add_signext_54 = sum13;
  assign add_signext_55 = $signed({{5{product20[20]}}, product20});
  assign add_temp_13 = add_signext_54 + add_signext_55;
  assign sum14 = add_temp_13[25:0];

  assign output_typeconvert = sum14[18:9];


  // Assignment Statements
  assign filter_out = output_typeconvert;

endmodule  // casfilt_stage2
